#!/bin/bash

save_file() {
    mv ~/"$1" ~/"$1".save
    if [ -f "$CONFIG_DIR/$1" ]
    then
        cp $CONFIG_DIR/"$1" ~/"$1"
    elif [ -d "$CONFIG_DIR/$1" ]
    then
        cp -r $CONFIG_DIR/"$1" ~/"$1"
    fi
}

unsave_file() {
    if [ -f ~/"$1" ]
    then
        rm ~/"$1"
    elif [ -d ~/"$1" ]
    then
        rm -r ~/"$1"
    fi
    mv ~/"$1".save ~/"$1"
}

if [ "$1" = "?" ]
then
    if [ -z "$CONFIG_DIR" ]
    then
        echo "Config is not loaded !"
    else
        echo "Config is loaded !"
    fi

elif [ "$1" = "load" ]
then
    if [ -z "$CONFIG_DIR" ]
    then
        export CONFIG_DIR="$HOME/.config/valentin_config"

        while read file
        do
            save_file "$file" 2>/dev/null
        done < <(sed -e "/^\s*#.*$/d" -e "/^\s*$/d" $CONFIG_DIR/.config/my_config/list_files)

        echo -e "\n"export CONFIG_DIR="$HOME/.config/valentin_config\n" >> ~/.bashrc

        # Must hide Sublime directory to not be detected as a Package
        mv $HOME/.config/sublime-text/Packages/User.save $HOME/.config/sublime-text/Packages/.User.save

        gnome-terminal --working-directory=$HOME --maximize
        kill -9 $PPID
    else
        echo "Config is already loaded !"
    fi

elif [ "$1" = "unload" ]
then
    if [ ! -z "$CONFIG_DIR" ]
    then
        # Unhide Sublime User directory (cf. load)
        mv $HOME/.config/sublime-text/Packages/.User.save $HOME/.config/sublime-text/Packages/User.save

        while read file
        do
            unsave_file "$file" 2>/dev/null
        done < <(sed -e "/^\s*#.*$/d" -e "/^\s*$/d" $CONFIG_DIR/.config/my_config/list_files)

        unset CONFIG_DIR

       gnome-terminal --working-directory=$HOME --maximize -- /bin/sh -c 'unset TMUX && bash'
       tmux kill-session
    else
        echo "Config is not loaded !"
    fi
else
    echo "Command $1 is not recognized"
fi
