#!/bin/bash

# Color aliases
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BOLD=$(tput smso)
UNBOLD=$(tput rmso)
RESET=$(tput sgr0)

# User general aliases
alias ll='ls -ahlF'
alias la='ls -A'
alias l='ls -CF'

alias pu="pushd"
alias po="popd"


alias configg="vim ~/.bashrc; source ~/.bashrc"
alias configgp="vim $XDG_CONFIG_HOME/bash/paths; source ~/.bashrc"
alias configp="vim $XDG_CONFIG_HOME/bash/local_paths; source ~/.bashrc"

alias configga="vim $XDG_CONFIG_HOME/bash/aliases; source ~/.bashrc"
alias configa="vim $XDG_CONFIG_HOME/bash/local_aliases; source ~/.bashrc"

alias configgf="vim $XDG_CONFIG_HOME/bash/functions; source ~/.bashrc"
alias configf="vim $XDG_CONFIG_HOME/bash/local_functions; source ~/.bashrc"

alias configgv="vim $XDG_CONFIG_HOME/bash/python_venv; source ~/.bashrc"

alias configgx="vim $XDG_CONFIG_HOME/bash/xdg_setup; source ~/.bashrc"

[ -x "$(command -v batcat)" ] && alias cat='batcat'
[ -x "$(command -v fd)" ] && alias fd='fd --color=auto --no-ignore --hidden --follow --exclude .git'

NOTES_DIR="$HOME/Documents/Notes"
alias td='[ -d "$NOTES_DIR" ] || mkdir -p "$NOTES_DIR" ; tmux rename-window "ToDo" 2> /dev/null; vim "$NOTES_DIR"/ToDo; tmux set-option automatic-rename on 2> /dev/null'

