#!/bin/bash

# Color aliases
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BOLD=$(tput smso)
UNBOLD=$(tput rmso)
RESET=$(tput sgr0)

# User general aliases
alias ll='ls -ahlF'
alias la='ls -A'
alias l='ls -CF'

alias pu="pushd"
alias po="popd"

NOTES_DIR="$HOME/Documents/Notes"
alias td='[ -d "$NOTES_DIR" ] || mkdir -p "$NOTES_DIR" ; tmux rename-window "ToDo" && vim "$NOTES_DIR"/ToDo && tmux set-option automatic-rename on'

alias py=python3
alias youtube-dl-video='youtube-dl --config-location ~/.config/youtube-dl/config_video'
alias youtube-dl-playlist='youtube-dl --config-location ~/.config/youtube-dl/config_playlist'

alias configa='vim ~/.config/bash/local_aliases; source ~/.bashrc'
alias configp='vim ~/.config/bash/local_path; source ~/.bashrc'
alias configg='vim ~/.bashrc; source ~/.bashrc'
alias configga='vim ~/.config/bash/aliases; source ~/.bashrc'
alias configgf='vim ~/.config/bash/functions; source ~/.bashrc'
alias configgp='vim ~/.config/bash/paths; source ~/.bashrc'

if command -v batcat > /dev/null
then
    alias cat='batcat'
    export MANPAGER="sh -c 'col -bx | batcat -l man -p --paging=always'"
fi
