#!/bin/bash

# Color aliases
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BOLD=$(tput smso)
UNBOLD=$(tput rmso)

# User general aliases
alias ll='ls -ahlF'
alias la='ls -A'
alias l='ls -CF'

alias cpr='cp -r'
alias rmr='rm -r'
alias cd..='cd ..'

alias pu="pushd"
alias po="popd"

NOTES_DIR="$HOME/Documents/Notes"
alias td='[ -d "$NOTES_DIR" ] || mkdir -p "$NOTES_DIR" ; tmux rename-window "ToDo" && vim "$NOTES_DIR"/ToDo && tmux set-option automatic-rename on'

alias py=python
alias youtube-dl-video='youtube-dl --config-location ~/.config/youtube-dl/config_video'

alias config='vim ~/.config/bash/local_aliases; source ~/.bashrc'
alias configg='vim ~/.bashrc; source ~/.bashrc'
alias configf='vim ~/.config/bash/functions; source ~/.bashrc'

