#!/bin/bash

alias jn=jupyter-notebook

alias cdp='cd ~/Documents/project-transporter'
alias tor='vim ~/Documents/project-transporter/Notes/ToRemember.md'

alias winmnt='sudo mount /dev/sda1 /media/valentin/DATA || sudo mount -o ro /dev/sda1 /media/valentin/DATA'
alias cdwin='cd /media/valentin/DATA'
alias visacc='winmount 2 &> /dev/null; libreoffice /media/valentin/DATA/Documents/Accounts.xlsx; sudo umount /media/valentin/DATA'

alias qmake='/usr/lib/qt5/bin/qmake'

alias bip='play -nq -t alsa synth 0.5 sine 1200 vol -8dB'

mkplay() {
    ls -1v "${1:-./}" | egrep ".(mp3|ogg|opus)" > "${1:-./}Playlist.m3u"
}

mp2ogg() {
    for file in *.mp3
    do
        ffmpeg -i "$file" -map a -c:a libvorbis -q:a 4 "${file/%mp3/ogg}"
    done
}

rmpic() {
    for file in **/*.ogg
    do
        mv "$file" "$file.backup"
        ffmpeg -i "$file.backup" -map a "$file"
    done
}

cop() {
    tmux rename-window ${1::-1}
    vim -O $1cpp $1hpp
}

number_music() {
    if [ -z "$1" ]
    then
        return
    fi
    mv "$1" "$({ ls *; echo 00.; } | egrep "^[0|1][0-9]\." | cut -c 1-2 | sort -rn | head -1 | xargs echo 1 + | bc | xargs printf "%02d"). $1"
    shift
    number_music "$@"
}

alias tb='docker run --rm -it -e "HOST_CW_DIR=${PWD}" -e "CALLING_HOST_NAME=$(hostname)" -e "CALLING_UID"=$UID -e "CALLING_OS"=$(uname) -v ${PWD}:/tb-module -v ${HOME}/.ssh:/root/.ssh -v /var/run/docker.sock:/var/run/docker.sock bitcraze/toolbelt'

# vim:syn=sh
