#!/bin/bash

mkdir -p "$HOME/.local/state/python/"
touch "$HOME/.local/state/python/venv_list"
curr_path="$(realpath "$(pwd)")"
while read vpath vname; do
    [[ "$curr_path/" != "$vpath/"* ]] && continue
    [[ ${#vpath} -lt ${#longest_match} ]] && continue
    longest_match="$vpath"
    venv_name="$vname"
done < "$HOME/.local/state/python/venv_list"

if [ -n "$venv_name" ]; then  # Venv found in venv_list
    source "$HOME/.local/venvs/$venv_name/bin/activate"
elif [ -d ".venv" ]; then  # Local venv found
    source ".venv/bin/activate"
    export PS1="(local) ${_OLD_VIRTUAL_PS1}"
else  # No venv found: activate base
    export VIRTUAL_ENV_DISABLE_PROMPT=1
    venv_path="$HOME/.local/venvs/base"
    if [ -d "$venv_path" ]; then
        source "$venv_path/bin/activate"
    else
        echo "No default virtual env created!"
    fi
fi
unset venv_path venv_name vpath vname longest_match curr_path

# Default REPL
py() {
    # Ptpython if it's available, in REPL or in interactive mode
    if [ -x "$(command -v ptpython)" ] && [[ $# == 0 || $# == 2 && $1 == -i ]]; then
        ptpython "$@"
    else
        python3 "$@"
    fi
}

toggle_python_debugger() {
    mkdir -p "$XDG_STATE_HOME/python"
    local state_file="$XDG_STATE_HOME/python/default_debugger"
    if [ -s "$state_file" ]
    then
        echo -n > "$state_file"
        unset PYTHONBREAKPOINT
    else
        echo pudb > "$state_file"
        export PYTHONBREAKPOINT=pudb.set_trace
    fi
}

# Default debugger
if [ -x "$(command -v pudb)" ] && grep -qs "pudb" "$XDG_STATE_HOME/python/default_debugger"
then
    export PYTHONBREAKPOINT=pudb.set_trace
fi

# Pdir2 config
export PDIR2_CONFIG_FILE="$XDG_CONFIG_HOME/python/pdir.conf"
