#!/bin/bash

export VIRTUAL_ENV_DISABLE_PROMPT=1

if [ -d "${PYTHON_VENV_PATH-$HOME/.local/venvs/base}" ]; then
    source "${PYTHON_VENV_PATH-$HOME/.local/venvs/base}"/bin/activate
fi

# Default REPL
py() {
    if [ -x "$(command -v ptpython)" ]; then
        ptpython "$@"
    else
        python3 "$@"
    fi
}

toggle_python_debugger() {
    mkdir -p "$XDG_STATE_HOME/python"
    local state_file="$XDG_STATE_HOME/python/default_debugger"
    if [ -s "$state_file" ]
    then
        echo -n > "$state_file"
        unset PYTHONBREAKPOINT
    else
        echo pudb > "$state_file"
        export PYTHONBREAKPOINT=pudb.set_trace
    fi
}

# Default debugger
if [ -x "$(command -v pudb)" ] && grep -qs "pudb" "$XDG_STATE_HOME/python/default_debugger"
then
    export PYTHONBREAKPOINT=pudb.set_trace
fi

# Pdir2 config
export PDIR2_CONFIG_FILE="$XDG_CONFIG_HOME/python/pdir.conf"
